<?php echo $block->getForm(); ?>
<button id="adcurve_submit_button" class="save primary a-right" onclick="confirm();">
    <span><?php echo __('Submit information and register to Adcurve'); ?></span>
</button>
<?php //** @TODO: Move styling to correct place (css file include) */ ?>
<style type="text/css">
	#popup_form_terms {
		border: 1px solid #535353;
		box-shadow: 6px 6px 3px #9a9a9a;
		background-color: #ebebeb;
		display: none;
		height: 260px;
		left: 20%;
		padding: 15px;
		position: fixed;
		top: 33%;
		width: 515px;
		z-index: 1;
	}
	#popup_form_terms ol li {
		margin-left: 20px;
	}
	#popup_form_terms button {
		display: inline-block;
		float: right;
	}
	#adcurve_submit_button {
		display: block;
		margin: 0 auto;
	}
</style>
<div id="popup_form_terms">
	<span class="admin__legend"><?php echo __('Thanks for your registration in Adcurve!'); ?></span>
	<span>
		<?php echo __('Adcurve helps you to advertise your products and to make your ads profitable.'); ?>
		<?php echo __('Adcurve also offers the option to insert orders in Magento.'); ?>
		<?php echo __('In order to do that, we ask you to grant access to:'); ?>
	</span>
	<ol>
		<li><?php echo __('Read product information to advertise your products and boost your sales'); ?></li>
		<li><?php echo __('Read order information to calculate the profitability of your ads'); ?></li>
		<li><?php echo __('Create a Integration user to insert orders in Magento from marketplaces'); ?></li>
	</ol>
	<button id="accepted" class="save primary" onclick="processForm();"><span><span><?php echo __('Accept');?></span></span></button>
</div>
<script type="text/javascript">
    //    <![CDATA[
    function confirm() {
        require(['jquery'], function($){
            $('#popup_form_terms').show();
		});
    }
    
    function processForm(){
    	require(['jquery'], function($){
	        $('#adcurve_registration_form').submit();
        });
    }
    //]]>
</script>