<?php if ($block->configHelper->shouldRenderTags()): ?>
    <?php
    	$product = $block->getCurrentProduct();
        $_productPriceInclTax = $this->tagHelper->getProductPriceInclTax($product);
        $_productPriceExclTax = $this->tagHelper->getProductPriceExclTax($product);
    ?>
    <!-- Start of Adcurve product page tag -->
    <script type="text/javascript">
        window.s2m_configuration = new Object();
        window.s2m_configuration.s2m_page = "product";
        window.s2m_configuration.s2m_customer_id = "<?php echo $block->tagHelper->getCustomerId(); ?>";
        window.s2m_configuration.s2m_email_hash = "<?php echo $block->tagHelper->getCustomerEmailHash(); ?>";
        window.s2m_configuration.s2m_product_id = "<?php echo $product->getId(); ?>";
        window.s2m_configuration.s2m_product_name = "<?php echo htmlspecialchars($product->getName(), ENT_QUOTES); ?>";
        window.s2m_configuration.s2m_amount_1 = "<?php echo $_productPriceInclTax; ?>";
        window.s2m_configuration.s2m_amount_2 = "<?php echo $_productPriceExclTax; ?>";
        window.s2m_configuration.s2m_stock = "<?php echo $block->getProductStock(); ?>";
    </script>
    <!-- End of Adcurve product page tag -->
<?php endif; ?>