<?php
$store = $block->getDefaultStore();
$installationTypeTest = $block->connectionHelper->getInstallationTypeTest();
$installationTypeLive = $block->connectionHelper->getInstallationTypeLive();
?>
<div class="adcurve-registration-status-tab entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('API connection status'); ?></h4>
    </div>

    <div class="fieldset">
        <div class="status-table-head">
            <div class="status-cell first">&nbsp;</div>
            <div class="status-cell">
                <span class="status-th"><?php echo __('Step 1: Registration'); ?> <span>
            </div>
            <div class="status-cell">
                <span class="status-th"><?php echo __('Step 2: Connection with Magento'); ?> <span>
            </div>
            <div class="status-cell">
                <span class="status-th"><?php echo __('Step 3: Connection with the Adcurve API'); ?> <span>
            </div>
            <div class="status-cell last">
                <span class="status-th"><?php echo __('Required steps'); ?> <span>
            </div>
        </div>

        <?php $storeList = $block->getAllStores();
        /** @var \Magento\Core\Model\Store $storeView */
        foreach ($storeList as $storeView) : ?>
            <?php $apiResult = $block->getApiConnectionStatus($storeView->getId()); ?>

            <div class="status-table-row">

                <ul class="status-bar">

                    <li class="status-cell first">
                     <span class="status-th"><?php echo $storeView->getName(); ?> <?php echo $block->getStoreInstalltionTypeStatus($storeView->getId())?><span>
                    </li>

                    <li class="status-cell status-bar-item <?php echo ($apiResult['stepsCompleted'] >= 1 ? 'status_success' : ($apiResult['stepsCompleted'] != 0 ? 'status_failure' : '')); ?>">
                        <span><?php echo ($apiResult['stepsCompleted'] >= 1); ?></span>

                    </li>

                    <li class="status-cell status-bar-item <?php echo ($apiResult['stepsCompleted'] >= 2 ? 'status_success' : ($apiResult['stepsCompleted'] != 0 ? 'status_failure' : '')); ?>">
                        <span><?php echo ($apiResult['stepsCompleted'] >= 2); ?></span>
                    </li>

                    <li class="status-cell status-bar-item <?php echo ($apiResult['stepsCompleted'] >= 3 ? 'status_success' : ($apiResult['stepsCompleted'] != 0 ? 'status_failure' : '')); ?>">
                        <span><?php echo ($apiResult['stepsCompleted'] >= 3); ?></span>
                    </li>

                    <li class="status-cell last">
                        <?php echo $apiResult['suggestion']; ?>
                    </li>

                </ul>

            </div>
        <?php endforeach; ?>
    </div>
</div>

<form id="adcurve_register_form" name="adcurve_register_form" onsubmit="return confirm();" action="<?php echo $block->configHelper->getRegisterUrl() ?>"  method="post">
    <input type="hidden" name="success_url" value="<?php echo $block->connectionHelper->getSuccessUrl($store->getId()) ?>"/>
    <input type="hidden" name="fail_url" value="<?php echo $block->connectionHelper->getFailUrl() ?>"/>
    <input type="hidden" name="wsdl_endpoint" value="<?php echo $block->getWsdlEndpoint() ?>"/>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo __('Register in AdCurve'); ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <colgroup class="label"></colgroup>
                <colgroup class="value"></colgroup>
                <tr>
                    <td class="label">
                        <label for="installation_type"><?php echo __('Installation type') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="radio" onClick="manageStoreInstallationMode()" class=" input-radio  validate-one-required-by-name" id="installation_type_live" name="shop[installation_type]" value="<?php echo $installationTypeLive;?>" checked="checked" /> <label class="inline" for="installation_type_live"><?php echo __('Live')?></label>
                        <input type="radio" onclick="manageStoreInstallationMode()" class=" input-radio  validate-one-required-by-name" id="installation_type_test" name="shop[installation_type]" value="<?php echo $installationTypeTest;?>" /> <label class="inline" for="installation_type_test"><?php echo __('Test')?></label>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><h3><?php echo __('Company Data') ?></h3></td>
                </tr>
                
                <tr>
                    <td class="label">
                        <label for="company_name"><?php echo __('Company Name ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="company_name" name="company[name]" value="<?php //echo $block->configHelper->(general/store_information/name); ?>" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="company_address"><?php echo __('Company Address ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="company_address" name="company[address]" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="company_city"><?php echo __('Company City ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="company_city" name="company[city]" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="company_country"><?php echo __('Company Country ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                    <?php $countries = $block->connectionHelper->getCountriesList(); ?>            
                    <?php if (count($countries) > 0): ?>
                        <select   class="select required-entry" id="company_country" name="company[country]" >
                            <option value="">-- Please Select --</option>
                            <?php foreach($countries as $country): ?>
                                <?php if(true)://$block->configHelper->(general/store_information/merchant_country) == $country['value']):?>
                                    <?php $selected = ' selected="selected" ';?>
                                <?php else:?>
                                    <?php $selected= '  ';?>
                                <?php endif;?>
                                <option <?php echo $selected;?> value="<?php echo $country['value'] ?>"><?php echo $country['label'] ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                        
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="company_region"><?php echo __('Company Region ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="company_region" name="company[region]" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="company_zipcode"><?php echo __('Company Zipcode ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="company_zipcode" name="company[zipcode]" />
                    </td>
                </tr>
                
                <tr>
                    <td colspan="2"><h3><?php echo __('Shop Data') ?></h3></td>
                </tr>
                <tr>
                    <td class="label">
                       <label for="store_switcher"><?php echo __('Choose Store View: ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <?php echo $block->getStoreSwitcherHtml(); ?>
                        <?php //echo Mage::getBlockSingleton('adminhtml/store_switcher')->getHintHtml(); ?>
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="shop_name"><?php echo __('Shop Name ') ?><span class="required">*</span></label></td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="shop_name" name="shop[name]" value="<?php //echo $block->configHelper->(general/store_information/name); ?>" />
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="shop_url"><?php echo __('Shop URL ') ?><span class="required">*</span></label></td>
                    <td class="value">
                        <input type="text" class="input-text required-entry validate-url" readonly="readonly" value="<?php echo $block->connectionHelper->getShopUrl($store); ?>" id="shop_url" name="shop[url]" />
                    </td>
                </tr>
                <tr>
                    <td class="label"><label for="shop_logo_url"><?php echo __('Shop Logo URL ') ?><span class="required">*</span></label></td>
                    <td class="value">
                        <input type="text" class="input-text required-entry validate-url" readonly="readonly" value="<?php echo $block->connectionHelper->getLogoUrl($store) ?>" id="shop_logo_url" name="shop[logo_url]" />
                    </td>
                </tr>
                <tr style="visibility:hidden; position:absolute; top: -9999px;">
                    <td class="label">
                        <label for="product_attributes"><?php echo __('Shop Attributes '); ?></label>
                    </td>
                    <td class="value">
                        <?php echo $block->getAttributeSelectHtml(); ?>
                    </td>
                </tr>
                <tr>
                    <td colspan="2"><h3><?php echo __('Contact Data') ?></h3></td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="contact_first_name"><?php echo __('Contact First Name ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="contact_first_name" name="contact[first_name]" value="<?php echo $block->getCurrentAdminUser()->getFirstname(); ?>" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="contact_last_name"><?php echo __('Contact Last Name ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="contact_last_name" name="contact[last_name]" value="<?php echo $block->getCurrentAdminUser()->getLastname(); ?>" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="contact_email"><?php echo __('Contact Email ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry validate-email" id="conact_email" name="contact[email]" value="<?php echo $block->getCurrentAdminUser()->getEmail(); ?>" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="contact_phone"><?php echo __('Contact Phone ') ?><span class="required">*</span></label>
                    </td>
                    <td class="value">
                        <input type="text" class="input-text required-entry" id="contact_phone" name="contact[phone]" value="<?php //echo $block->configHelper->(general/store_information/phone); ?>" />
                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <button id="adcurve_submit_button" type="submit">
                            <span><span><span><?php echo __('Confirm'); ?></span></span></span></button>
                    </td>
                </tr>
            </table>
        </div>
    </div>    
    <input type="hidden" name="shop[soap_username]"  id="soap_username" value=""  />
    <input type="hidden" name="shop[soap_api_key]"  id="soap_api_key" value=""  />
    
    <?php
        $availAbleStores = $block->connectionHelper->getStoresInstallationModeList();
        
        $liveMode = implode(",", $availAbleStores[$installationTypeLive]);
        $testMode = implode(",", $availAbleStores[$installationTypeTest]);
        
    ?>
     
    <input type="hidden" name="mode_list_<?php echo $installationTypeLive; ?>"  id="mode_list_<?php echo $installationTypeLive; ?>" value="<?php echo $liveMode; ?>"  />
    <input type="hidden" name="mode_list_<?php echo $installationTypeTest; ?>"  id="mode_list_<?php echo $installationTypeTest; ?>" value="<?php echo $testMode; ?>"  />
</form>

<div id="popup_form_terms">
    <h2>Thanks for your registration in Adcurve!</h2>
    <p>Adcurve helps you to advertise your products and to make your ads profitable. Adcurve also offers the option to insert orders in Magento. In order to do that, we ask you to grant access to:</p>
    <ol>
      <li>read product information to advertise your products and boost your sales </li>
      <li>read order information to calculate the profitability of your ads</li>
      <li>create a SOAP API user to insert orders in Magento from marketplaces</li>
    </ol>
 
    <button id="accepted" onclick="processForm();"><span><span><?php echo __('Accept');?></span></span></button>
    
</div>

<div class="validation-advice" id="advice-required-theme-name" style="display:none;"><?php echo __('Theme label can\'t be empty'); ?></div>
<script type="text/javascript">
    //    <![CDATA[

    function manageStoreInstallationMode()
    {
        var form = new varienForm('adcurve_register_form');
        var url = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/adcurveAdminhtml_registration/getStoresInstallationMode") ?>';
        var currentMode = $$('input:checked[type=radio][name=shop[installation_type]]')[0].value;
        
            
            new Ajax.Request(url,
                {
                    method: 'post',

                    onSuccess: function (data) {
                        var modes = data.responseText.evalJSON(true);
                        
                        if(modes.<?php echo $installationTypeLive; ?>!=null){
                            
                            $('mode_list_<?php echo $installationTypeLive; ?>').setValue(modes.<?php echo $installationTypeLive; ?>.toString());
                        }
                        else{
                            $('mode_list_<?php echo $installationTypeLive; ?>').setValue("");
                        }
                        
                        if(modes.<?php echo $installationTypeTest; ?>!=null){
                            
                            $('mode_list_<?php echo $installationTypeTest; ?>').setValue(modes.<?php echo $installationTypeTest; ?>.toString());
                        }
                        else{
                            $('mode_list_<?php echo $installationTypeTest; ?>').setValue("");
                        }
                        
                        
                        var storeViewAdvice = $('advice-required-store-switcher');
                        if (storeViewAdvice != null) {
                            //storeViewAdvice.remove();
                            //$('advice-required-submit-button').remove();
                            //$('adcurve_submit_button').style.display = 'inline-block';
                        }
                    }
                });
                
                
                var test_stores_list =  $('mode_list_test').getValue();
                var storesid = test_stores_list.split(",");
                var available_stores = getAvailableStores();
                
                storesid.each(function(op){
                    
                    if(test_stores_list != "") {
                    
                        var option = op.split(":");                    
                        var ov = option[0];
                        var ot = "\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0" + option[1] ;
                            
                        if(available_stores.length > 0) {

                            if (available_stores.indexOf(ov) == -1 && ov != "") {
                                if(currentMode == '<?php echo $installationTypeLive; ?>') {
                                    createStoreOption(ov, ot, 0);
                                } else {
                                    removeStoreOption(ov, ot);
                                }
                            } else if(available_stores.indexOf(ov) !== -1  && currentMode == '<?php echo $installationTypeTest; ?>'){
                                removeStoreOption(ov, ot);
                            }
                            
                        }
                        else {
                            
                            if ( ov != "") {
                                if(currentMode == '<?php echo $installationTypeLive; ?>') {
                                    createStoreOption(ov, ot, 0);
                                } else {
                                    removeStoreOption(ov, ot);
                                }
                            
                            }
                        }
                    }
                });
            
        
    }
    
    manageStoreInstallationMode();
    
    function getAvailableStores()
    {
        var available_stores = [];
        
        $$('#store_switcher option').each(function(op){
            available_stores.push(op.value);
        });
        
        return available_stores;    
    }
    
    function createStoreOption(option_value, option_text, option_index)
    {
        // get reference to select element
        var sel = document.getElementById('store_switcher');

        // create new option element
        var opt = document.createElement('option');

        // create text node to add to option element (opt)
        opt.appendChild( document.createTextNode(option_text) );

        // set value property of opt
        opt.value = option_value; 

        // add opt to end of select box (sel)
        sel.appendChild(opt); 
    }
    
    function removeStoreOption(option_value, option_text)
    {
        
        var sel = document.getElementById("store_switcher");
        
        for (var i = 0; i < sel.length; i++){
        
            if (sel.options[i].value == option_value ){
                sel.remove(i);
                break;
            }
        }

    }
    
    function showForm(id)
    {
        win = new Window({ title: "Thanks for your registration in Adcurve!", zIndex:3000, destroyOnClose: false, recenterAuto:false, resizable: false, width:515, height:260, minimizable: true, maximizable: true, draggable: true});
        win.setContent(id, false, true);
        win.showCenter();
        
        $('popup_form_terms').setStyle({display:'block'});
        return false;
    }
 
    var form = new varienForm('adcurve_register_form');
    var url = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/adcurveAdminhtml_registration/getUrls") ?>';
    
    if($('store_switcher').value == null || $('store_switcher').value == ""){
        $('adcurve_submit_button').style.display = 'none';
    }
    $('store_switcher').on('change', function (event, element) {
        new Ajax.Request(url,
            {
                method: 'post',
                parameters: {"id_store": element.getValue()},
                onSuccess: function (data) {
                    var urls = data.responseText.evalJSON(true);
                    $('shop_url').setValue(urls.shop_url);
                    $('shop_logo_url').setValue(urls.shop_logo_url);
                    $(document.getElementsByName('success_url')[0]).setValue(urls.success_url);

                    var storeViewAdvice = $('advice-required-store-switcher');
                    if (storeViewAdvice != null) {
                        storeViewAdvice.remove();
                        $('advice-required-submit-button').remove();
                        $('adcurve_submit_button').style.display = 'inline-block';
                    }

                    if (urls.is_registered == '1' && urls.mode == '<?php echo $installationTypeTest; ?>') {
                        var div = document.createElement('div');
                        div.innerHTML = '<?php echo __('This store view is already registered at Adcurve. Please contact Adcurve for support.'); ?>';
                        div.id = 'advice-required-store-switcher';
                        div.className = 'validation-advice';

                        $('store_switcher').parentNode.appendChild(div);

                        var divbutton = document.createElement('div');
                        divbutton.innerHTML = '<?php echo __('This store view is already registered at Adcurve. Please contact Adcurve for support.'); ?>';
                        divbutton.id = 'advice-required-submit-button';
                        divbutton.className = 'validation-advice';

                        $('adcurve_submit_button').parentNode.appendChild(divbutton);
                        $('adcurve_submit_button').style.display = 'none';
                    }
                }
            })
    });

    function confirm() {
        var form = new varienForm('adcurve_register_form');
        var storeIdValue = $('store_switcher').getValue();
        var attributesValue = $(document.getElementById('product_attributes')).getValue();
        var saveAttributesUrl = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/adcurveAdminhtml_registration/saveShopAttributes") ?>';
        if (storeIdValue == "" || storeIdValue == null){
            return false;
        }
        if (form.validator && form.validator.validate()){
            showForm('popup_form_terms');
        }
        else{
            return false;
        }
        
        return false;
    }
        
        
    function processForm(){
        var storeIdValue = $('store_switcher').getValue();
        var installation_type = $$('input:checked[type="radio"][name="shop[installation_type]"]').pluck('value'); //$('shop[installation_type]').getValue();
        var c_fname = $('contact_first_name').getValue();
        var c_lname = $('contact_last_name').getValue();
        var c_email = $('conact_email').getValue();
        var c_phone = $('contact_phone').getValue();
        
        var contact = {first_name:c_fname, last_name:c_lname, email:c_email, phone:c_phone};
        
        var attributesValue = $(document.getElementById('product_attributes')).getValue();
        var saveAttributesUrl = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/adcurveAdminhtml_registration/saveShopAttributes") ?>';
        if (storeIdValue == "" || storeIdValue == null){
            return false;
        }
        new Ajax.Request(saveAttributesUrl,
            {
                method: 'post',
                parameters: {"id_store": storeIdValue, "installation_type": installation_type, "shop_attributes": JSON.stringify(attributesValue), "contact" : JSON.stringify(contact)},
                onSuccess: function (data) {
                    var result = data.responseText.evalJSON(true);
                    var failedValidationCount = document.getElementsByClassName('validation-failed').length;

                    if (result.status == 'success' && failedValidationCount <= 0) {
                        var isUserCreated = createUser();
                        
                    }
                }
        });
    }
    
    function createUser(){
        var url = '<?php //echo Mage::helper("adminhtml")->getUrl("adminhtml/adcurveAdminhtml_registration/createUser") ?>';
        var form = new varienForm('adcurve_register_form');
        var storeIdValue = $('store_switcher').getValue();
        new Ajax.Request(url,
            {
                method: 'post',
                parameters: {"id_store": storeIdValue},
                onSuccess: function (data) {
                    var res = data.responseText.evalJSON(true);                        
                    if(res.status=='success' || res.status == 'already_success'){
                        $('soap_api_key').setValue(res.user_info.api_key);
                        $('soap_username').setValue(res.user_info.username);
                        
                        form.submit();
                        return true;
                    } else {
                        return false;
                    }
                }
            });
         return false;

    }

    $('store_switcher').dispatchEvent(new Event('change'));
    //    ]]>
    
</script>