<?php
/**
 * @var \Adcurve\Adcurve\Block\System\Config\Fieldset\SupportTab $block
 */
?>
<?php $_newTicketUrl          = $block->getNewTicketUrl(); ?>
<?php $_installationManualUrl = $block->getInstallationManualUrl(); ?>
<?php $_changelogUrl          = $block->getChangelogUrl(); ?>
<?php $_kbUrl                 = $block->getKbUrl(); ?>
<?php $_version               = $block->configHelper->getModuleVersion(); ?>

<?php $_documentation		  = $block->getDocumentationUrl()?>
<?php $_publishers            = $block->getPublishersUrl(); ?>
<?php $_features              = $block->getFeaturesUrl(); ?>
<?php $_pricing               = $block->getPricingUrl(); ?>
<?php $_email                 = $block->getContactEmail(); ?>
<?php $_phone                 = $block->getContactPhone(); ?>
<span style="font-size:18px;"><strong><?php echo sprintf(__('Adcurve plugin %s'), $_version); ?></strong></span>
<table id="supportWrap" cellpadding="0" cellspacing="0">
    <tr>
        <td>
            <div>
                <p>
                    <?php echo __('The ultimate platform to connect, analyse and optimise your digital marketing channels.'); ?>
                </p>
                <span>
                    <ul style="margin-left: 20px;">
                        <li><?php echo __('Connect your products with shoppers'); ?></li>
                        <li><?php echo __('Analyse to get real insights'); ?></li>
                        <li><?php echo __('Optimise your advertising'); ?></li>
                    </ul>
                </span>
                <p><?php echo __('AdCurve provides a free tier for up to 3 advertising channels for shops with up to 15.000 products.'); ?></p>
                <p><?php echo __('More information and pricing can be found at <a href="https://adcurve.com">https://adcurve.com</a>'); ?></p>
			</div>
			 
			 
        </td>
        <td>&nbsp;</td>
        <td class="value">
            <div>
                <strong><?php echo __('Version compatibility'); ?></strong>
                <ul style="list-style:none;">
                    <li><?php echo __('Magento Community Edition version'); ?>: <span class="version">v2.4</span> </li>
                    <li><?php echo __('Magento Enterprise Edition version') ; ?>: <span class="version">v2.1</span> </li>
                </ul>
            <div>
            <br />
            <div>
                <strong><?php echo __('Contact adcurve'); ?></strong>
				<ul style="list-style:none;">
                    <li><?php echo __('Email'); ?>: <a href="mailto:<?php echo $_email; ?>"><?php echo $_email; ?></a></li>
                </ul>
            <div>
        </td>
    </tr>
</table>